package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.CervicalCancer;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface CervicalCancerService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_cancer
     *
     * @mbg.generated Fri Aug 02 15:12:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_cancer
     *
     * @mbg.generated Fri Aug 02 15:12:03 CST 2019
     */
    int insert(CervicalCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_cancer
     *
     * @mbg.generated Fri Aug 02 15:12:03 CST 2019
     */
    int insertSelective(CervicalCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_cancer
     *
     * @mbg.generated Fri Aug 02 15:12:03 CST 2019
     */
    CervicalCancer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_cancer
     *
     * @mbg.generated Fri Aug 02 15:12:03 CST 2019
     */
    int updateByPrimaryKeySelective(CervicalCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_cancer
     *
     * @mbg.generated Fri Aug 02 15:12:03 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CervicalCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_cancer
     *
     * @mbg.generated Fri Aug 02 15:12:03 CST 2019
     */
    int updateByPrimaryKey(CervicalCancer record);

    /**
     * 分页获取宫颈癌表
     * @param pageParam
     * @return
     */
    PageInfo<CervicalCancer> selectPageInfo(CervicalCancer record, PageParam pageParam);

    int insertData(CervicalCancer record);
}