package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.CervicalEpithelioma;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface CervicalEpitheliomaService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_epithelioma
     *
     * @mbg.generated Fri Aug 02 15:12:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_epithelioma
     *
     * @mbg.generated Fri Aug 02 15:12:50 CST 2019
     */
    int insert(CervicalEpithelioma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_epithelioma
     *
     * @mbg.generated Fri Aug 02 15:12:50 CST 2019
     */
    int insertSelective(CervicalEpithelioma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_epithelioma
     *
     * @mbg.generated Fri Aug 02 15:12:50 CST 2019
     */
    CervicalEpithelioma selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_epithelioma
     *
     * @mbg.generated Fri Aug 02 15:12:50 CST 2019
     */
    int updateByPrimaryKeySelective(CervicalEpithelioma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cervical_epithelioma
     *
     * @mbg.generated Fri Aug 02 15:12:50 CST 2019
     */
    int updateByPrimaryKey(CervicalEpithelioma record);

    /**
     * 分页获取宫颈上皮肉瘤表
     * @param pageParam
     * @return
     */
    PageInfo<CervicalEpithelioma> selectPageInfo(CervicalEpithelioma record, PageParam pageParam);

    int insertData(CervicalEpithelioma record);

}