package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.Choriocarcinoma;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface ChoriocarcinomaService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choriocarcinoma
     *
     * @mbg.generated Fri Aug 02 15:13:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choriocarcinoma
     *
     * @mbg.generated Fri Aug 02 15:13:37 CST 2019
     */
    int insert(Choriocarcinoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choriocarcinoma
     *
     * @mbg.generated Fri Aug 02 15:13:37 CST 2019
     */
    int insertSelective(Choriocarcinoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choriocarcinoma
     *
     * @mbg.generated Fri Aug 02 15:13:37 CST 2019
     */
    Choriocarcinoma selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choriocarcinoma
     *
     * @mbg.generated Fri Aug 02 15:13:37 CST 2019
     */
    int updateByPrimaryKeySelective(Choriocarcinoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choriocarcinoma
     *
     * @mbg.generated Fri Aug 02 15:13:37 CST 2019
     */
    int updateByPrimaryKey(Choriocarcinoma record);

    /**
     * 分页获取绒癌表
     * @param pageParam
     * @return
     */
    PageInfo<Choriocarcinoma> selectPageInfo(Choriocarcinoma record, PageParam pageParam);

    int insertData(Choriocarcinoma record);

}