package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.EndometrialCancerField;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface EndometrialCancerFieldService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer_field
     *
     * @mbg.generated Fri Aug 02 15:01:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer_field
     *
     * @mbg.generated Fri Aug 02 15:01:19 CST 2019
     */
    int insert(EndometrialCancerField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer_field
     *
     * @mbg.generated Fri Aug 02 15:01:19 CST 2019
     */
    int insertSelective(EndometrialCancerField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer_field
     *
     * @mbg.generated Fri Aug 02 15:01:19 CST 2019
     */
    EndometrialCancerField selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer_field
     *
     * @mbg.generated Fri Aug 02 15:01:19 CST 2019
     */
    int updateByPrimaryKeySelective(EndometrialCancerField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer_field
     *
     * @mbg.generated Fri Aug 02 15:01:19 CST 2019
     */
    int updateByPrimaryKey(EndometrialCancerField record);

    /**
     * 分页获取子宫内膜癌字段表
     * @param pageParam
     * @return
     */
    PageInfo<EndometrialCancerField> selectPageInfo(EndometrialCancerField record, PageParam pageParam);

    int insertData(EndometrialCancerField record);


}