package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.EndometrialCancer;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface EndometrialCancerService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer
     *
     * @mbg.generated Fri Aug 02 15:15:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer
     *
     * @mbg.generated Fri Aug 02 15:15:29 CST 2019
     */
    int insert(EndometrialCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer
     *
     * @mbg.generated Fri Aug 02 15:15:29 CST 2019
     */
    int insertSelective(EndometrialCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer
     *
     * @mbg.generated Fri Aug 02 15:15:29 CST 2019
     */
    EndometrialCancer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer
     *
     * @mbg.generated Fri Aug 02 15:15:29 CST 2019
     */
    int updateByPrimaryKeySelective(EndometrialCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer
     *
     * @mbg.generated Fri Aug 02 15:15:29 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(EndometrialCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endometrial_cancer
     *
     * @mbg.generated Fri Aug 02 15:15:29 CST 2019
     */
    int updateByPrimaryKey(EndometrialCancer record);

    /**
     * 分页获取子宫内膜癌表
     * @param pageParam
     * @return
     */
    PageInfo<EndometrialCancer> selectPageInfo(EndometrialCancer record, PageParam pageParam);

    int insertData(EndometrialCancer record);

}