package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.HydatidMole;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface HydatidMoleService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hydatid_mole
     *
     * @mbg.generated Fri Aug 02 15:01:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hydatid_mole
     *
     * @mbg.generated Fri Aug 02 15:01:26 CST 2019
     */
    int insert(HydatidMole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hydatid_mole
     *
     * @mbg.generated Fri Aug 02 15:01:26 CST 2019
     */
    int insertSelective(HydatidMole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hydatid_mole
     *
     * @mbg.generated Fri Aug 02 15:01:26 CST 2019
     */
    HydatidMole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hydatid_mole
     *
     * @mbg.generated Fri Aug 02 15:01:26 CST 2019
     */
    int updateByPrimaryKeySelective(HydatidMole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hydatid_mole
     *
     * @mbg.generated Fri Aug 02 15:01:26 CST 2019
     */
    int updateByPrimaryKey(HydatidMole record);

    /**
     * 分页获取葡萄胎表
     * @param pageParam
     * @return
     */
    PageInfo<HydatidMole> selectPageInfo(HydatidMole record, PageParam pageParam);

    int insertData(HydatidMole record);
}