package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.PortugueseInvasion;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface PortugueseInvasionService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portuguese_invasion
     *
     * @mbg.generated Fri Aug 02 15:20:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portuguese_invasion
     *
     * @mbg.generated Fri Aug 02 15:20:56 CST 2019
     */
    int insert(PortugueseInvasion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portuguese_invasion
     *
     * @mbg.generated Fri Aug 02 15:20:56 CST 2019
     */
    int insertSelective(PortugueseInvasion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portuguese_invasion
     *
     * @mbg.generated Fri Aug 02 15:20:56 CST 2019
     */
    PortugueseInvasion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portuguese_invasion
     *
     * @mbg.generated Fri Aug 02 15:20:56 CST 2019
     */
    int updateByPrimaryKeySelective(PortugueseInvasion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portuguese_invasion
     *
     * @mbg.generated Fri Aug 02 15:20:56 CST 2019
     */
    int updateByPrimaryKey(PortugueseInvasion record);


    /**
     * 分页获取侵葡表
     * @param pageParam
     * @return
     */
    PageInfo<PortugueseInvasion> selectPageInfo(PortugueseInvasion record, PageParam pageParam);


    int insertData(PortugueseInvasion record);
}