package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.Sarcoma;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface SarcomaService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sarcoma
     *
     * @mbg.generated Fri Aug 02 15:21:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sarcoma
     *
     * @mbg.generated Fri Aug 02 15:21:24 CST 2019
     */
    int insert(Sarcoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sarcoma
     *
     * @mbg.generated Fri Aug 02 15:21:24 CST 2019
     */
    int insertSelective(Sarcoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sarcoma
     *
     * @mbg.generated Fri Aug 02 15:21:24 CST 2019
     */
    Sarcoma selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sarcoma
     *
     * @mbg.generated Fri Aug 02 15:21:24 CST 2019
     */
    int updateByPrimaryKeySelective(Sarcoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sarcoma
     *
     * @mbg.generated Fri Aug 02 15:21:24 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Sarcoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sarcoma
     *
     * @mbg.generated Fri Aug 02 15:21:24 CST 2019
     */
    int updateByPrimaryKey(Sarcoma record);

    /**
     * 分页获取肉瘤表
     * @param pageParam
     * @return
     */
    PageInfo<Sarcoma> selectPageInfo(Sarcoma record, PageParam pageParam);

    int insertData(Sarcoma record);
}