package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.UterineSarcoma;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface UterineSarcomaService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uterine_sarcoma
     *
     * @mbg.generated Fri Aug 02 15:23:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uterine_sarcoma
     *
     * @mbg.generated Fri Aug 02 15:23:08 CST 2019
     */
    int insert(UterineSarcoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uterine_sarcoma
     *
     * @mbg.generated Fri Aug 02 15:23:08 CST 2019
     */
    int insertSelective(UterineSarcoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uterine_sarcoma
     *
     * @mbg.generated Fri Aug 02 15:23:08 CST 2019
     */
    UterineSarcoma selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uterine_sarcoma
     *
     * @mbg.generated Fri Aug 02 15:23:08 CST 2019
     */
    int updateByPrimaryKeySelective(UterineSarcoma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uterine_sarcoma
     *
     * @mbg.generated Fri Aug 02 15:23:08 CST 2019
     */
    int updateByPrimaryKey(UterineSarcoma record);

    /**
     * 分页获取子宫内瘤表
     *
     * @param pageParam
     * @return
     */
    PageInfo<UterineSarcoma> selectPageInfo(UterineSarcoma record, PageParam pageParam);

    int insertData(UterineSarcoma record);

}