package com.fancy.cancer.api.service;

import com.fancy.cancer.api.po.VulvarCancers;
import com.fancy.cancer.common.utils.PageParam;
import com.github.pagehelper.PageInfo;

public interface VulvarCancersService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vulvar_cancers
     *
     * @mbg.generated Fri Aug 02 15:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vulvar_cancers
     *
     * @mbg.generated Fri Aug 02 15:23:43 CST 2019
     */
    int insert(VulvarCancers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vulvar_cancers
     *
     * @mbg.generated Fri Aug 02 15:23:43 CST 2019
     */
    int insertSelective(VulvarCancers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vulvar_cancers
     *
     * @mbg.generated Fri Aug 02 15:23:43 CST 2019
     */
    VulvarCancers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vulvar_cancers
     *
     * @mbg.generated Fri Aug 02 15:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(VulvarCancers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vulvar_cancers
     *
     * @mbg.generated Fri Aug 02 15:23:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(VulvarCancers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vulvar_cancers
     *
     * @mbg.generated Fri Aug 02 15:23:43 CST 2019
     */
    int updateByPrimaryKey(VulvarCancers record);

    /**
     * 分页获取外阴癌表
     * @param pageParam
     * @return
     */
    PageInfo<VulvarCancers> selectPageInfo(VulvarCancers record, PageParam pageParam);

    int insertData(VulvarCancers record);

}